from typing import Dict, Any

class MelcloudHeatPump:
    def __init__(self, data: Dict[str, Any]):
        dev = data.get("Device", {})
        if dev.get("DeviceType") != 1:
            raise ValueError("Not a Heat Pump device")
        self.defrost_mode = dev.get("DefrostMode")
        self.heat_pump_frequency = dev.get("HeatPumpFrequency")
        self.room_temperature_zone1 = dev.get("RoomTemperatureZone1")
        self.outdoor_temperature = dev.get("OutdoorTemperature")
        self.flow_temperature = dev.get("FlowTemperature")
        self.flow_temperature_zone1 = dev.get("FlowTemperatureZone1")
        self.flow_temperature_boiler = dev.get("FlowTemperatureBoiler")
        self.return_temperature = dev.get("ReturnTemperature")
        self.return_temperature_zone1 = dev.get("ReturnTemperatureZone1")
        self.return_temperature_boiler = dev.get("ReturnTemperatureBoiler")
        self.boiler_status = dev.get("BoilerStatus")
        self.booster_heater1_status = dev.get("BoosterHeater1Status")
        self.booster_heater2_status = dev.get("BoosterHeater2Status")
        self.booster_heater2plus_status = dev.get("BoosterHeater2PlusStatus")
        self.immersion_heater_status = dev.get("ImmersionHeaterStatus")
        self.water_pump1_status = dev.get("WaterPump1Status")
        self.water_pump2_status = dev.get("WaterPump2Status")
        self.water_pump3_status = dev.get("WaterPump3Status")
        self.tank_water_temperature = dev.get("TankWaterTemperature")
        self.eco_hot_water = dev.get("EcoHotWater")
        self.power = dev.get("Power")
        self.operation_mode = dev.get("OperationMode")
        self.operation_mode_zone1 = dev.get("OperationModeZone1")
        self.target_hc_temperature_zone1 = dev.get("TargetHCTemperatureZone1")
        self.forced_hot_water_mode = dev.get("ForcedHotWaterMode")
        self.prohibit_hot_water = dev.get("ProhibitHotWater")
        self.current_energy_mode = dev.get("CurrentEnergyMode")
